apiVersion: apps/v1
kind: Deployment
metadata:
  name: go-config-map
  labels:
    app: go-config-map
spec:
  replicas: 1
  selector:
    matchLabels:
      app: go-config-map
  template:
    metadata:
      name: go-config-map
      labels:
        app: go-config-map
    spec:
      containers:
        - name: go-config-map-container
          image: ranjit013/test-configmap:latest
          imagePullPolicy: Always
          ports:
            - containerPort: 8080
              protocol: TCP
          env:
            - name: CONFIG_MAP_VALUE
              valueFrom:
                 configMapKeyRef:
                   name: my-config
                   key: config.json
      restartPolicy: Always

      